compile_pdf:
  image: aergus/latex
  script:
    - latexmk -pdf Main.tex
  artifacts:
    paths:
      - Main.pdf

pages:
  stage: deploy
  script:
    - mkdir public  # create a folder called public
    - cp Main.pdf public/Crystalline_comparison_theorem_for_p-divisible_groups.pdf
  artifacts:
    paths: 
      - public  # instruct GitLab to keep the public folder
  only: 
    - master  # deploy the pdf only for commits made to the master branch
